pipeline {
    agent {
        any {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Building') {
            steps {
                // sh 'mvn -B -DskipTests clean package'
                echo "today session is jenkins"
            }
        }
        stage('Testing') {
            steps {
                echo "running test stage successfully"
            }
            // post {
            //     always {
            //         junit 'target/surefire-reports/*.xml'
            //     }
            // }
        }
        stage('Deploying') {
            steps {
                echo "deployment is success"
            }
        }
    }
}
